package Ventas;


/**
* Ventas/VentaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from venta.idl
* sábado 10 de noviembre de 2018 04:17:42 PM COT
*/

public abstract class VentaPOA extends org.omg.PortableServer.Servant
 implements Ventas.VentaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarVenta", new java.lang.Integer (0));
    _methods.put ("actualizarVenta", new java.lang.Integer (1));
    _methods.put ("eliminarProveedor", new java.lang.Integer (2));
    _methods.put ("consultarProveedor", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Ventas/Venta/insertarVenta
       {
         int id = in.read_long ();
         int producto_id = in.read_long ();
         String cantidad = in.read_wstring ();
         int precio = in.read_long ();
         boolean $result = false;
         $result = this.insertarVenta (id, producto_id, cantidad, precio);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Ventas/Venta/actualizarVenta
       {
         int id = in.read_long ();
         int producto_id = in.read_long ();
         String cantidad = in.read_wstring ();
         int precio = in.read_long ();
         boolean $result = false;
         $result = this.actualizarVenta (id, producto_id, cantidad, precio);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Ventas/Venta/eliminarProveedor
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarProveedor (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Ventas/Venta/consultarProveedor
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultarProveedor (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Ventas/Venta/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Ventas/Venta:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Venta _this() 
  {
    return VentaHelper.narrow(
    super._this_object());
  }

  public Venta _this(org.omg.CORBA.ORB orb) 
  {
    return VentaHelper.narrow(
    super._this_object(orb));
  }


} // class VentaPOA
