package Ventas;


/**
* Ventas/Venta.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from venta.idl
* sábado 10 de noviembre de 2018 04:17:43 PM COT
*/

public interface Venta extends VentaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Venta
