package Ventas;


/**
* Ventas/VentaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from venta.idl
* sábado 10 de noviembre de 2018 04:17:43 PM COT
*/

public interface VentaOperations 
{
  boolean insertarVenta (int id, int producto_id, String cantidad, int precio);
  boolean actualizarVenta (int id, int producto_id, String cantidad, int precio);
  boolean eliminarProveedor (int id);
  String consultarProveedor (int id);
  void shutdown ();
} // interface VentaOperations
