module Ventas {

    interface Venta{

        boolean insertarVenta(in long id_venta,in wstring cliente_id, in long producto_id, in long  precio, in long cantidad);
        
        boolean actualizarVenta(in long id, in long  producto_id , in wstring cantidad, in long  precio ); 

        boolean eliminarProveedor(in long id);
       
        oneway void shutdown();
        
    };

};
